name: C++ CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.1.0'
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: C++ generation
      run: |
        mkdir bin
        cd bin
        cmake ../src -G "Visual Studio 16 2019" -DCMAKE_PREFIX_PATH=%Qt6_DIR%
        MSBuild.exe .\tic-tac-toe.vcxproj /p:Configuration=Debug
        MSBuild.exe .\tic-tac-toe.vcxproj /p:Configuration=Release
        MSBuild.exe .\tic-tac-toe.vcxproj /p:Configuration=RelWithDebInfo
        MSBuild.exe .\tic-tac-toe.vcxproj /p:Configuration=MinSizeRel
    - name: Generate windows package
      run: |
        mkdir package
        move bin/Release/tic-tac-toe.exe package/
        move bin/*.png package/
        windeployqt ./package/tic-tac-toe.exe
    - uses: actions/upload-artifact@v2
      with:
        name: Tic-tac-toe executable for windows
        path: package/
